# Generated by Django 4.1.5 on 2023-01-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='ilosc_ocen',
        ),
        migrations.RemoveField(
            model_name='film',
            name='srednia_ocena',
        ),
    ]
