# Generated by Django 4.1.5 on 2023-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocena', '0002_remove_film_ilosc_ocen_remove_film_srednia_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='srednia_ocena',
            field=models.FloatField(default=0.0),
        ),
    ]
